### ISSUE TITLE
[Setup] Installing basic React modules

### ISSUE THREAD

**Issue by haesookim** [swsnu/swpp2019-team5#1]
- [x] react-redux & redux
- [x] react-router & react-router-dom
- [x] connected-react-router
- [x] axios
- [x] node-sass   

* SASS/SCSS: CSS를 전처리해주는 라이브러리입니다! 아래 링크들을 참조해서 사용하면 될 것 같아요 :) 
(기본적으로는 nested css같은 느낌으로!)
[SASS Website](https://sass-lang.com/)
[SASS docs](https://sass-lang.com/documentation)

* 현재 모든 패키지는 yarn 을 사용하여 설치했습니다. npm과 yarn을 섞어 쓸 경우 모든 패키지가 날아가는 일이 간혹 있다고 하니 yarn으로 가급적 통일해서 사용합시다!

**Comment by ttoru96** [comment]
LGTM
