### ISSUE TITLE
[Bug Report] 메인 화면 이미지에서 sign in sign up 이 눌리지 않습니다

### ISSUE THREAD

**Issue by vionicbest** [swsnu/swpp2019-team5#110]
![image](https://user-images.githubusercontent.com/38846024/70226580-6f696c00-1794-11ea-9346-b770cbb00e3d.png)

**Comment by iamsungyeonjoo** [comment]
감사합니다~~ :)

**Comment by eodmsabc** [comment]
크롬 개발자 도구를 켜는 등 화면 비율이 바뀌면 클릭이 되네요

**Comment by haesookim** [comment]
현재 아래쪽 이미지에 가려지는 상황인 것 같습니다! 추후 수정하도록 하겠습니다 :) 감사합니다!!
