### ISSUE TITLE
[Bug Report] create problem

### ISSUE THREAD

**Issue by deploy-soon** [swsnu/swpp2019-team5#112]
![image](https://user-images.githubusercontent.com/44163510/70226732-b0fa1700-1794-11ea-80a7-bfe1260b3f28.png)

사진 등록을 하려 했지만 카테고리 추가가 안되었다고 하는데 등록 조건이 완화되면 좋겠습니다

**Comment by haesookim** [comment]
앗 태그에서 엔터를 눌러 주세요! 태그가 등록되지 않은 상태입니다ㅠㅠ
