### ISSUE TITLE
로그인 후 회원가입/로그인 페이지

### ISSUE THREAD

**Issue by HaeTheong** [swsnu/swpp2019-team5#115]
로그인 하고 회원가입, 로그인 페이지를 주소를 쳐서 들어갔을 때 리다이렉션이 있으면 좋을 것 같아요

추가로 아래 그림처럼 메인에서 가운데 버튼들이 가려져서 안눌리네요
![image](https://user-images.githubusercontent.com/14370645/70226771-c7a06e00-1794-11ea-8a7c-b5a240838857.png)

**Comment by ttoru96** [comment]
리다이렉션 로직도 추가하겠습니다 피드백 감사합니다!!
