### ISSUE TITLE
[Request] 어떤 부분이 ml feature인가요?

### ISSUE THREAD

**Issue by vionicbest** [swsnu/swpp2019-team5#116]

**Comment by iamsungyeonjoo** [comment]
옷 사진을 올리고나서 confirm proceed 누르면 ml이 알아서 사진 안에 있는 item의 카테고리와 태그들을 detect 해줍니다

**Comment by vionicbest** [comment]
감사합니다! 지금 다른 사진을 넣었을 때 t shirt를 자동으로 잡아주는 것을 확인했어요
