### ISSUE TITLE
각 게시물에 이모티콘(?)

### ISSUE THREAD

**Issue by abcthing** [swsnu/swpp2019-team5#117]
각 게시물에 무표정같은 이모티콘이 있는데 무엇을 의미하는 것인지 이해하기가 힘든 것 같아요

**Comment by haesookim** [comment]
create/edit 시 좌상단에서 수정할 수 있는 satisfaction value입니다! 피드백 감사합니다 :) 더 이해가 쉽도록 바꾸겠습니다!
