### ISSUE TITLE
[Bug Report] Invalid Date

### ISSUE THREAD

**Issue by deploy-soon** [swsnu/swpp2019-team5#118]
![image](https://user-images.githubusercontent.com/44163510/70226922-0afadc80-1795-11ea-93a8-80507a1542d6.png)

달력 클릭 후 

![image](https://user-images.githubusercontent.com/44163510/70226958-1bab5280-1795-11ea-9588-5e84013b4d3d.png)

invalid date이 뜨는 조건이 궁금합니다.

**Comment by iamsungyeonjoo** [comment]
아 그날은 outfit을 정하지 않아서 그렇습니다. 그런 경우에는 클릭이 되지 않도록 수정하겠습니다.
감사합니다.
