### ISSUE TITLE
달력 사용법..

### ISSUE THREAD

**Issue by peterhyun** [swsnu/swpp2019-team5#120]
Invalid date를 클릭하면 아예 그 페이지로 이동이 안되게 하는 게 더 좋을 것 같습니다... 

<img width="942" alt="Screen Shot 2019-12-05 at 7 29 23 PM" src="https://user-images.githubusercontent.com/22678965/70227210-8ceb0580-1795-11ea-88a6-fbb47c16982c.png">

이 페이지 너무 못생겼기 때문에...ㅋㅋㅋ

alert 메시지를 띄운다든지 하면 좋을 것 같아요.

**Comment by haesookim** [comment]
감사합니다! 수정하도록 하겠습니다 :)
