### ISSUE TITLE
[Bug report]

### ISSUE THREAD

**Issue by 1207koo** [swsnu/swpp2019-team5#121]
1. 아이콘 클릭 시 메인 화면으로 가지지 않습니다. 애초에 링크가 걸려있는 것 같이 마우스가 모양이 바뀌는데 링크가 걸려있지 않습니다.
2. 0B짜리 아무것도 없는 파일이 올려집니다
3. Edit 버튼의 인식 범위가 이상합니다. 위쪽 20%정도만 버튼 판정이 있습니다.
4. 태그를 추가하다보니 더 추가가 안되길래 x를 눌렀더니 태그를 추가하는 곳 자체가 사라졌습니다. 한글 태그 넣어서 그럴 수 도 있습니다

**Comment by haesookim** [comment]
1. 은 혹시 어느 화면 기준으로 말씀하시는 걸까요? (로그인 후에는 browse/search가 메인화면에 해당하는데, 이 경우라면 알려주시면 감사드리겠습니다!

이외의 버그 및 사용성 문제는 수정하겠습니다! 감사합니다.
