### ISSUE TITLE
사진 업로드

### ISSUE THREAD

**Issue by uyw4687** [swsnu/swpp2019-team5#122]
사진 업로드하면 사진 말고 밑에 검은색 여백이 더 나와요!!

**Comment by haesookim** [comment]
감사합니다!
혹시 이미지 사이즈나, 스크린샷 같은 것을 보여주실 수 있을까요?

**Comment by uyw4687** [comment]
일시적인 버그였나봐요. 재현이 안 되네요. 그 대신 edit 페이지에서 이미지 잘리는 현상만 보이네요!!

**Comment by haesookim** [comment]
이미지가 잘린다고 하는 것이 혹시 어떤 뜻이실까요?ㅠㅠㅠ (스크린샷 올려주셔도 괜찮습니다!!)
친절한 피드백 정말 감사합니다 🙏

**Comment by uyw4687** [comment]
![image](https://user-images.githubusercontent.com/41810398/70682164-3f185500-1ce1-11ea-94eb-fa7f69b70d79.png)
![image](https://user-images.githubusercontent.com/41810398/70682182-493a5380-1ce1-11ea-9cc6-17a0b7f9377c.png)
밑이 원래 이미지 위가 잘린 이미지입니다~
마무리 홧팅하세요~!
