### ISSUE TITLE
로그인/회원가입 관해서 개선이 필요해 보입니다.

### ISSUE THREAD

**Issue by njsh4261** [swsnu/swpp2019-team5#124]
1. 회원가입 버튼을 누르고 메인 페이지로 나온 다음 sign in을 해야 하는 것 같던데, 회원가입이 완료되면 로그인이 바로 되면 좋을 것 같습니다.
2. 회원가입 시 이미 존재하는 이메일을 입력한 경우 새로운 이메일을 넣었을 때 반응 메시지가 뜨지 않습니다.
3. 전반적으로 로그인/회원가입 관련 기능에 대한 반응이 느리다는 느낌을 받았습니다. 제 환경에서는 3~5초 정도 걸리는 것 같던데 속도 측면에서 개선이 필요해 보입니다.

**Comment by haesookim** [comment]
감사합니다! 피드백 반영하여 수정하겠습니다.
혹시 2. 와 관련해서, 어떤 반응 메시지를 말씀하시는 것인지 알려주실 수 있나요?
