### ISSUE TITLE
[Bug] ML response is parsed wrong

### ISSUE THREAD

**Issue by haesookim** [swsnu/swpp2019-team5#127]
t shirt 같은 경우 't' 태그와 'shirt' 태그로 분리됨

**Comment by ttoru96** [comment]
ML API 에서 리턴되는 값을 스페이스 기준으로 파싱해서 생긴 결과인 거 같습니다
스페이스 기준으로 파싱하는 대신 '-'을 넣는 것으로 바꿀게요
 예) t-shirt 가 리턴됨
