### ISSUE TITLE
[Question] Category types

### ISSUE THREAD

**Issue by iamsungyeonjoo** [swsnu/swpp2019-team5#28]
저희 카테고리가 지금 논의 된거는
 Upper Body, Lower Body, Full Body, Accessories이렇게 네가진데 

1) Outer
2) Top
3) Bottom 
4) Dress 
5) Shoes
6) Bag 
7) Accessory
 
이렇게 7개로 하면 어떨까용 의견주세요!

**Comment by haesookim** [comment]
개인적으로는 > Bag/accessory가 합쳐져도 큰 상관이 없을 것 같아요!
Dress 대신 One Piece라고 말하는 건 어떨까요?? 드레스는 아닌 원피스가 있을 수도 있지 않을까(??) 해서!

**Comment by ttoru96** [comment]
저는 옷의 종류로 나누기 보다는, 신체 부위 중 어디를 덮느냐가 기준이 되면 더 명확할 거라고 생각했거든요. 
그래서 처음에 Upper Body, Lower Body, Full Body, Accessories 처럼 네 개로 제안했던 이유가, Outer도 Dress도 Full body에 들어가게 되니까 명확하고도 간단하다고 생각해서였습니다

**Comment by iamsungyeonjoo** [comment]
아하 그렇군요 제가 여러 쇼핑몰 돌아다니다가 공통적으로 쓰는 분류라서 제안을 했던건데
유저 입장에서는 그냥 신체부위로 하는 것도 명확하고 좋겠네요!! 그리고 해수 말대로 가방을 악세사리로 합쳐도 좋을 것 같네요!!

그런데 outer의 경우 상의 까지만 걸쳐지는 옷도 있고, 롱페딩 같이 긴것도 있으니까
Outer, Upper Boddy, Lower Body, Full Body, Accessories로 합치면 어떨까요?
