### ISSUE TITLE
[BugFix]Missing Dependency for MySQL

### ISSUE THREAD

**Issue by ttoru96** [swsnu/swpp2019-team5#29]
태원님이 고쳐서 머지하신 백엔드 모델 관련 코드 ( #19 ) 깃풀받아서 돌려보니까 트래비스에서 'cannot import MySQL' 에러가 뜨는데요.디비를 mysql로 바꾸면서 설치했던 디펜던시를 requirements.txt에 안 적어줘서 발생하는 에러같습니다. requirements.txt에 디펜던시 명시해주세요.

**Comment by dreammerkr** [comment]
django-python 연동에 사용된 mysqlclient 를 requirement.txt에 추가하였습니다.
