### ISSUE TITLE
[User Auth] User model choices

### ISSUE THREAD

**Issue by haesookim** [swsnu/swpp2019-team5#31]
우리는 Django default user model을 사용할 예정인가요 아니면 우리의 model을 따로 만드나요?
Login/Logout을 만드는 시점에서 이에 대한 결정이 필요할 것 같습니다.

그리고 현재 item/outfit/tag model이 별도의 app으로 분리되어 있기 때문에, user도 따로 구분하려고 하는데, 이렇게 진행하면 되는지 확인해 주시면 감사하겠습니다!

**Comment by ttoru96** [comment]
장고의 default user model을 만들든 커스텀해서 사용하든, user도 별도의 app으로 분리하는 게 reasonable 해 보입니다
