### ISSUE TITLE
[Question] Edit outfit과 관련하여 질문!

### ISSUE THREAD

**Issue by iamsungyeonjoo** [swsnu/swpp2019-team5#75]
![image](https://user-images.githubusercontent.com/33143827/69127598-df69c800-0aed-11ea-81dd-a0fc9683c7e9.png)
저희가 xd로 아이디어 구상할 때 edit page에서 edit for all / edit for single outfit 두가지 모드를 모두 지원하기로 했습니다. 그런데 지금 막상 구현하려고 보니 다시 고려해야할 것들이 떠올라 공유하고자 합니다.

**1. Tag를 수정하거나 지울때마다 매번 for all인지 for single인지 결정하는 것이 번거롭지 않을까요?**

     -1) 행여 tag를 수정할때마다가 아니라 아이템 하나를 원하는 만큼 다 수정하고 나서 결정하더라 
       도 결국 confirm edit 버튼이 따로 있어서 outfit의 수정을 마치는 시점과 다른 시점에 edit mode 
       를 매번 결정해주는게 귀찮을 것 같습니다

     -2) 실수로 edit for all 을 눌러서, 다시 edit for single로 돌아가고 싶을 때도 난감할 것 같습니다

**2. 어떤 item을 한번에 다 수정하고 싶을때는 outfit edit page가 아니라 아예 browse page의 search bar 옆에 trim item? edit item 즉, 저장된 item을 한번에 다 바꿔주는 기능을 가진 버튼을 따로 두는 것은 어떤지요?**  
   
     -1) Button을 hover하면 tooltip으로 간단한 설명을 보여주어 user가 이해할 수 있도록 하면 도움 
        이 될 것 같습니다.
 
     -2)  XD만들때  category 수정할 때  edit for all 인지 for single인지 결정하게 할 지는 논의를 안했 
       던 것 같습니다.  category도 모든 outfit에 들어가 있는 item에 대해 다 바꿔주고 싶으면 trim 
        item 버튼 눌러서 하면 좋을 것 같습니다.

**Comment by dreammerkr** [comment]
2의 한번에 다 바꿔주는 기능은 아이템을 선택해야하는데 그건 search bar input으로 처리하나요 아니면 기타 다른 input을 넣어주나요?

**Comment by haesookim** [comment]
흠 이게 browse에 들어가야 하는지는 확실히 그림이 안 그려지네요! 지적해주신 부분들은 맞는 말 같아서, 일단 기획에 수정은 있어야 할 것 같습니당... 내일 한 번 더 이야기 나눠보아요!

**Comment by ttoru96** [comment]
1-1) 두 번 선택을 해야한다는 귀찮음은, 이 기능이 브라우저에 생겨도 동일할 거 같긴 해요..! select for all, select for this outfit 기능을 모두 지원하는 이상 어쩔 수 없다고도 생각됩니다ㅠ
1-2) 프론트에서는 select for all, select for this outfit 버튼을 각각 눌렀을 때 유저의 선택을 변수로만 저장을 해두고, 실제로 confirm edit을 눌렀을 때만 백엔드로 보내지고 디비에서 실제 업데이트가 이뤄질 거라고 생각했는데요..! 이런 식의 프로세스면 유저가 confirm edit 버튼을 누르기 전까지는 select for all, select for this outfit 사이를 마음껏 선택할 수 있을 거 같아요 또 유저가 선택하고 나서 edit for all을 선택했는지 edit for this outfit을 선택했는지 옆에 작게 글씨로 보여줄 수 있으면 좋을 거같아요
2-1) 위의 해수님 말대로 이게 브라우저의 어디에 들어갈 수 있는지 잘 상상이 안 됩니다만, 내일 회의에서 의논해보아요
2-2) 카테고리 자체를 수정하게 된다면 꽤 큰 변화인거 같아서요 아예 그 아이템을 지우는 방식으로 유저가 접근하지 않을까요?? 지금 드는 생각은 카테고리에서의 수정을 막는 것도 하나의 방법일 거 같아요
