### ISSUE TITLE
[Create] Selected Weather API check

### ISSUE THREAD

**Issue by haesookim** [swsnu/swpp2019-team5#85]
createrOutfit 시 날짜를 지정하면
getWeather() 말고  getSpecificDayWeather(date)를 부르는지, 이 때 API call result 정상적으로 나오는지 확인해주세요!

**Comment by iamsungyeonjoo** [comment]
hotfix/create-outfit 브랜치 파서 하겠습니다

- [ ]  : date를 수정할때 getSpecificDayWeather(date) 하기

- [ ]  : upload image 와 연결하기 (with 소영이가 만든 upload-image-to-backend브랜치)

**Comment by haesookim** [comment]
Upload Image Container 에서 item이 0개 와도 자동으로 하나 생성해주기 << 는 ML에서 아무것도 안 와도 라는 뜻인가요?

**Comment by iamsungyeonjoo** [comment]
넹
